// Generated by nitro

// App Config
import type { Defu } from 'defu'



type UserAppConfig = Defu<{}, []>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}
  interface NitroRuntimeConfig {
   database: {
      url: string,
   },

   redis: {
      url: string,
   },

   s3: {
      endpoint: string,

      region: string,

      bucket: string,

      accessKeyId: string,

      secretAccessKey: string,
   },

   public: {
      apiBase: string,

      appUrl: string,
   },
  }
}
export {}