// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/**:all': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/auth/[...all]').default>>>>
    }
    '/api/posts/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/posts/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/posts/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/posts/[id].patch').default>>>>
    }
    '/api/posts/:id/like': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/posts/[id]/like.post').default>>>>
    }
    '/api/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/posts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/posts/index.post').default>>>>
    }
    '/api/posts/trending': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/posts/trending.get').default>>>>
    }
    '/api/test-email': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/test-email.post').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/upload.post').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/users/index.get').default>>>>
    }
    '/api/users/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/api/users/me.get').default>>>>
    }
    '/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/health.get').default>>>>
    }
  }
}
export {}